version: '3'

volumes:
  db-volume:
    driver: local
    driver_opts:
      device: /home/wochae/data/db-data
      type: none
      o: bind
  wp-volume:
    driver: local
    driver_opts:
      device: /home/wochae/data/wp-data
      type: none
      o: bind
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    restart: always
    networks:
      - intra
    volumes:
      - db-volume:/var/lib/mysql
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - 443:443
    restart: always
    networks:
      - intra
    volumes:
      - wp-volume:/var/www/html
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    restart: always
    networks:
      - intra
    volumes:
      - wp-volume:/var/www/html
    depends_on:
      - mariadb
networks:
  intra:
    driver: bridge