version: '3'

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: always
        volumes:
            - DB:/var/lib/mysql
        env_file:
            - .env
        networks:
            - intra
        expose:
            - "3306"

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        restart: always
        depends_on:
            - mariadb
        volumes:
            - WP:/var/www/wordpress
        env_file:
            - .env
        networks:
            - inception
        expose: 
            - "9000"

    nginx:
        container_name: nginx
        build: ./requirements/nginx
        restart: always
        depends_on:
            - wordpress
        volumes:
            - WP:/var/www/wordpress
        networks:
            - inception
        ports:
            - "443:443"
volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/wochae/42_docker/inception_data/mariadb
  WP:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/wochae/42_docker/inception_data/wordpress

networks:
  inception:
    driver: bridge