FROM debian:buster

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
        mariadb-clinet \
        wget \
        curl \
        php7.3-fpm \
        php-cli \
        php-mysql \
        vim